# Generated by Django 4.2.16 on 2024-10-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayMonthlyTimeSlotPassengerCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=10)),
                ('sttn', models.CharField(max_length=20)),
                ('hr_4_get_on_nope', models.FloatField()),
                ('hr_4_get_off_nope', models.FloatField()),
                ('hr_5_get_on_nope', models.FloatField()),
                ('hr_5_get_off_nope', models.FloatField()),
                ('hr_6_get_on_nope', models.FloatField()),
                ('hr_6_get_off_nope', models.FloatField()),
                ('hr_7_get_on_nope', models.FloatField()),
                ('hr_7_get_off_nope', models.FloatField()),
                ('hr_8_get_on_nope', models.FloatField()),
                ('hr_8_get_off_nope', models.FloatField()),
                ('hr_9_get_on_nope', models.FloatField()),
                ('hr_9_get_off_nope', models.FloatField()),
                ('hr_10_get_on_nope', models.FloatField()),
                ('hr_10_get_off_nope', models.FloatField()),
                ('hr_11_get_on_nope', models.FloatField()),
                ('hr_11_get_off_nope', models.FloatField()),
                ('hr_12_get_on_nope', models.FloatField()),
                ('hr_12_get_off_nope', models.FloatField()),
                ('hr_13_get_on_nope', models.FloatField()),
                ('hr_13_get_off_nope', models.FloatField()),
                ('hr_14_get_on_nope', models.FloatField()),
                ('hr_14_get_off_nope', models.FloatField()),
                ('hr_15_get_on_nope', models.FloatField()),
                ('hr_15_get_off_nope', models.FloatField()),
                ('hr_16_get_on_nope', models.FloatField()),
                ('hr_16_get_off_nope', models.FloatField()),
                ('hr_17_get_on_nope', models.FloatField()),
                ('hr_17_get_off_nope', models.FloatField()),
                ('hr_18_get_on_nope', models.FloatField()),
                ('hr_18_get_off_nope', models.FloatField()),
                ('hr_19_get_on_nope', models.FloatField()),
                ('hr_19_get_off_nope', models.FloatField()),
                ('hr_20_get_on_nope', models.FloatField()),
                ('hr_20_get_off_nope', models.FloatField()),
                ('hr_21_get_on_nope', models.FloatField()),
                ('hr_21_get_off_nope', models.FloatField()),
                ('hr_22_get_on_nope', models.FloatField()),
                ('hr_22_get_off_nope', models.FloatField()),
                ('hr_23_get_on_nope', models.FloatField()),
                ('hr_23_get_off_nope', models.FloatField()),
                ('hr_0_get_on_nope', models.FloatField()),
                ('hr_0_get_off_nope', models.FloatField()),
                ('hr_1_get_on_nope', models.FloatField()),
                ('hr_1_get_off_nope', models.FloatField()),
                ('hr_2_get_on_nope', models.FloatField()),
                ('hr_2_get_off_nope', models.FloatField()),
                ('hr_3_get_on_nope', models.FloatField()),
                ('hr_3_get_off_nope', models.FloatField()),
            ],
            options={
                'db_table': 'subway_monthly_time_slot_passenger_counts',
            },
        ),
    ]
