# Generated by Django 5.1.1 on 2024-10-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayDailyTimeSlotPassengerDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('line_number', models.CharField(max_length=10)),
                ('station_name', models.CharField(max_length=10)),
                ('time_slot', models.CharField(max_length=20)),
                ('difference', models.IntegerField()),
            ],
            options={
                'db_table': 'subway_daily_time_slot_passenger_difference',
            },
        ),
    ]
