# Generated by Django 5.1.2 on 2024-10-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_degreeofsubwaycongestion'),
        ('data_collection', '0002_subwaydailytimeslotpassengerdifference'),
    ]

    operations = [
    ]
