# Generated by Django 5.1.2 on 2024-10-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_merge_20241016_1906'),
        ('data_collection', '0003_subwaydailytimeslotpassengerdifference_latitude_and_more'),
    ]

    operations = [
    ]
