# Generated by Django 5.1.1 on 2024-10-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0003_merge_20241016_2249"),
        ("data_collection", "0005_subwayamenities_and_more"),
    ]

    operations = []
