# Generated by Django 5.1.2 on 2024-10-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('line_number', models.CharField(max_length=20)),
                ('cultural_space', models.BooleanField(default=False)),
                ('wheelchair_lift', models.BooleanField(default=False)),
                ('meeting_spot', models.BooleanField(default=False)),
                ('parking_lot', models.BooleanField(default=False)),
                ('bike_rack', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('ticket_office', models.BooleanField(default=False)),
                ('civil_service', models.BooleanField(default=False)),
                ('currency_exchange', models.BooleanField(default=False)),
                ('nursing_room', models.BooleanField(default=False)),
            ],
        ),
    ]
