# Generated by Django 5.1.2 on 2024-10-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='line_number',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='station_name',
            new_name='sttn',
        ),
    ]
